spring:
  application:
    name: catchTable
  datasource:
    url: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 50
  devtools:
    restart:
      enabled: true
  thymeleaf:
    cache: false
  web:
    resources:
      static-locations: file:/var/www
  servlet:
    multipart:
      enabled: true
      max-file-size: 1GB
      max-request-size: 2GB
      file-size-threshold: 10MB
      location: /var/www/files/tmp

  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
      use_sql_comments: true
    show-sql: true

  data:
    redis:
      host: redis
      port: 6379

server:
  servlet:
    context-path: /v1/api
  error:
    include-message: always

logging:
  level:
    org.hibernate.SQL: DEBUG
    root: info

jwt:
  ACCESS_SECRET: ${JWT_SECRET}
  ACCESS_EXPIRATION: 60 * 60 * 1000
  REFRESH_EXPIRATION: 7 * 24 * 60 * 60 * 1000

file:
  pre-fix-path: /var/www/files