package com.catchtable.dynamo.domain;

import java.time.LocalDateTime;
import lombok.AccessLevel;
import lombok.Builder;
import lombok.Getter;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedTimestampAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbImmutable;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSortKey;

@Getter
@Builder
@DynamoDbImmutable(builder = UserSegment.UserSegmentBuilder.class)
public class UserSegment {

    @Getter(AccessLevel.NONE)
    private Integer userId;

    @Getter(AccessLevel.NONE)
    private Integer segmentId;

    @Getter(AccessLevel.NONE)
    private LocalDateTime createdAt;

    private Long expirationAt;

    @DynamoDbPartitionKey
    public Integer getUserId() {
        return this.userId;
    }

    @DynamoDbSortKey
    public Integer getSegmentId() {
        return this.segmentId;
    }

    @DynamoDbAutoGeneratedTimestampAttribute
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }
}
