version: "3.8"

services:
  # LocalStack - AWS Mock
  localstack:
    container_name: awslocal
    image: localstack/localstack
    ports:
      - "4566:4566"            # LocalStack Gateway
    environment:
      - SERVICES=s3, dynamodb
      - DEBUG=1
      - DEFAULT_REGION=us-east-1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - app-network

  # Spring Boot App
  my_project:
    build:
      context: ../
      dockerfile: ./docker/app/Dockerfile
    container_name: spring-project
    ports:
      - "8080:8080"
    volumes:
      - ../:/app
    env_file:
      - ../.env
    networks:
      - app-network
    depends_on:
      - localstack
      - mysql
      - redis

  # Redis
  redis:
    build:
      context: ../
      dockerfile: docker/redis/Dockerfile
    container_name: redis-project
    ports:
      - "6379:6379"
    networks:
      - app-network

  # MySQL
  mysql:
    build:
      context: ../
      dockerfile: docker/mysql/Dockerfile
    container_name: mysql-project
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
